name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
    SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
    WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}
    ROOT_DIR: ${{ secrets.ROOT_DIR }}
    AML_ENV_NAME: ${{ secrets.AML_ENV_NAME }}
    MODEL_NAME: ${{ secrets.MODEL_NAME }}
    MODEL_DESCRIPTION: ${{ secrets.MODEL_DESCRIPTION }}
    TRAINING_TESTING_DATASET: ${{ secrets.TRAINING_TESTING_DATASET }}
    EXPERIMENT_NAME: ${{ secrets.EXPERIMENT_NAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Set up python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
     
      - name: "install dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: "Fix auth error"
        run: |
          python -m pip install -U --force-reinstall pip pip install azure-cli==2.29

      - name: "Azure login"  
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Preporcess data"
        working-directory: "steps"
        run: |
          python 01_DataProcessing.py
      
      - name: "Training model"
        working-directory: "steps"
        run: |
          python 02_TrainModel.py
          
      - name: "Register model"
        working-directory: "steps"
        run: |
          python 03_RegisterModel.py
          
      - name: "Deploy model"
        working-directory: "steps"
        run: |
          python 04_DeployModel.py
        


      
